### ISSUE TITLE
This plugin does not work with groups containing spaces or multibyte strings.

### ISSUE THREAD

**Issue by tanakakz-alpha** [mittelab/ifauthex-dokuwiki-plugin#1]
We are using ADFS SAML authentication, and there are users with groups containing spaces and multibyte characters.
I attempted to use this group with the ifauthex plugin, but I can not display it well.

**Comment by 5p4k** [comment]
There are two different limitations:

1. The string manipulation functions are not multibyte
2. Space splits tokens

I think I can fix 1. by using the `mb_` counterpart of the string functions (assuming PCRE was compiled for multibyte).

For 2. I think the easiest solution would be to allow quoting groups or users, such as in `@"space group" && ! "johnson&&johnson"`. The other option would be to escape all special tokens, but I don’t like much `"@space\ group &&! abc\\\\\ def"`.

Can you post an example of a group name/user name you have in your setup? I’ll use it in the unit tests.

**Comment by tanakakz-alpha** [comment]
We tested with the following two.

domain users
経営企画本部 企画部

**Comment by 5p4k** [comment]
I finally found the time to go after this one!  
I released v0.2, with support for multibyte strings, as well as quoting, for names containing spaces (see https://www.dokuwiki.org/plugin:ifauthex#quoting_names).

I'll close this issue for now, but feel free to comment and reopen if I left out something. Thank you!
