### ISSUE TITLE
Is the documentation page clear

### ISSUE THREAD

**Issue by mrhelbig** [mittelab/ifauthex-dokuwiki-plugin#11]
Hi,

I've just started playing around with your plugin, and wanted to ask a clarifying questions about this comment on the module [documentation page](https://www.dokuwiki.org/plugin:ifauthex).

`The content is not truly hidden, it is just not rendered (it is still visibile on the source). To truly hide use the [nodisp](https://www.dokuwiki.org/plugin:nodisp) plugin.`

I'm using FireFox, and when I view the page source for a page that restricts some content using this syntax:
```
<ifauth @trusted_group>
sensitive stuff
</ifauth>
```
... I don't see the `sensitive stuff` in the HTML. So when you say that the hidden content is still visible in the source, I was wondering what you meant? Did you mean the page contents sent to the end user's browser, or did you instead mean the DokuWiki source that is made available through the ?do=edit action?

Sorry if, I'm being a bit dense.

Thanks
Alex

**Comment by 5p4k** [comment]
Hi Alex, I meant the DokuWiki source -- anyone who can access the source text will be able to see `sensitive stuff`. Also "render" refers to the synthesis of the HTML page by the server, not to the visualization performed by the browser.

**Comment by mrhelbig** [comment]
Thanks for the clarification. I understand your meaning now.

Cheers
