### ISSUE TITLE
Feature request - add style information

### ISSUE THREAD

**Issue by mrhelbig** [mittelab/ifauthex-dokuwiki-plugin#14]
Hi, Ive just started using ifauthex. I was wondering if there might be a way to include an optional  style name in the syntax so we can reflect that when required in the rendered page.

For example, the following:
`<ifauth @staff style-name>This is secret stuff, only for staff</ifauth>`
could be used to enclose the hidden text with a styled DIV.

Just a thought.

Thanks

**Comment by 5p4k** [comment]
Hi! Thanks for the input!

However, I'd like to keep the functionality of this plugin limited and clearly defined (hide content depending on who is viewing), and leave the actual formatting out. Interaction with surrounding tags is tricky, and styling a div is just one possible formatting case out of infinitely many, definitely insufficient for even e.g. displaying a [bootstrap alert](https://www.dokuwiki.org/plugin:bootswrapper#alert).

The intended way to do content formatting would be within the the `<ifauth ...>...</ifauth>` wrappers, e.g.
```
<ifauth @staff>
<panel type="info" title="Staff only">
  Customized staff message
</panel>
</ifauth>
```
