### ISSUE TITLE
Compatibility after update to Release rc2-2020-06-01 "Hogfather" RC2

### ISSUE THREAD

**Issue by JonTester** [mittelab/ifauthex-dokuwiki-plugin#5]
Hi Pietro,
the following error occured after updating.
Catchable fatal error: Argument 1 passed to AST\tokenize() must be an instance of AST\string, string given, called in C:\inetpub\wwwroot\dokuwiki\lib\plugins\ifauthex\lib\grammar.php on line 202 and defined in C:\inetpub\wwwroot\dokuwiki\lib\plugins\ifauthex\lib\tokenizer.php on line 134

I changed the following to get it running again. Perhaps you could check an patch it.
OLD
function auth_expr_parse($expr) {
    return \AST\parse(\AST\tokenize($expr, auth_expr_all_tokens(), auth_expr_ignore_tokens()), auth_expr_all_elements());
}
NEW
function auth_expr_parse(AST\string $expr) {
    return \AST\parse(\AST\tokenize($expr, auth_expr_all_tokens(), auth_expr_ignore_tokens()), auth_expr_all_elements());
}

**Comment by 5p4k** [comment]
I also observed issues with the new release candidate, but this doesn't seem to be related.

From what I can see on [StackOverflow](https://stackoverflow.com/questions/4103480/how-to-resolve-must-be-an-instance-of-string-string-given-prior-to-php-7) it looks like this occurs on PHP versions prior to 7, where it was not possible to type hint `string`. Which version of PHP are you using?

**Comment by 5p4k** [comment]
Besides this issue, the plugin is currently **not working** with the latest RC2 "Hogfather". This is however a [known issue of Dokuwiki](https://github.com/splitbrain/dokuwiki/issues/3146), which will be fixed by [this pull](https://github.com/splitbrain/dokuwiki/pull/3132).

**Comment by JonTester** [comment]
Hi Pietro,

you are right. Looks like I’m using an 5.6 Version of PHP. But with this your ifauthex is working in Hogfather RC2.
Updating on 7.x I get a lot of messages that no access is allowed to anyone, but for this messages I have to check which part they come from.

**Comment by 5p4k** [comment]
PHP 5.6 is within the requirements of Dokuwiki, so I would still fix the issue. If you still have the 5.6 install, could you try if the following change fixes it?

Change `lib/tokenizer.php:134` from:
`function tokenize(string $text, array $tokDefs, array $stripTokDefs) {`
to
`function tokenize(text, array $tokDefs, array $stripTokDefs) {`

**Comment by JonTester** [comment]
Hi Pietro,

Looks good. You just have a $ missing in front of text.
My line
function tokenize($text, array $tokDefs, array $stripTokDefs) {

In grammar.php I changed the line 201 to
function auth_expr_parse($expr) {

I now work on getting up to PHP 7.*.

Thanks for your help.

**Comment by 5p4k** [comment]
The new Hogfather RC3 is out, and the plugin seems to be working fine with it.

I also pushed the change for fixing compatibility with PHP 5.6. Until the next release, if you do not manage to update PHP, you can still install the master branch version of the plugin using this URL: 
https://github.com/mittelab/ifauthex-dokuwiki-plugin/archive/master.zip

I will close this issue; if the problem persists, feel free to reopen this or open a new one!

**Comment by JonTester** [comment]
Hi Pietro,
thanks for the message.

Works on my server with php 5.6 and now php 7.x.

Thanks for your work.

Mit freundlichen Grüßen / Kind regards,

Michael Stahl
Softwareentwickler
IT-Solutions

Fresenius Kabi Deutschland GmbH
Zeppelinstrasse 1c
85375 Neufahrn
P +49 8165 901-420
michael.stahl@fresenius-kabi.com
www.fresenius-kabi.com/de<http://www.fresenius-kabi.com/de>

Link zu gesellschaftsrechtlichen Pflichtangaben und Vertraulichkeitshinweis / Link to corporate information and confidentiality notice
https://www.fresenius.de/Fresenius_Kabi_Deutschland_GmbH
Link zu Datenschutzinformationen / Link to Privacy Statement
https://www.fresenius-kabi.com/de/datenschutz

Von: EXTERN Pietro Saccardi <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 00:32
An: mittelab/ifauthex-dokuwiki-plugin <ifauthex-dokuwiki-plugin@noreply.github.com>
Cc: Michael Stahl <Michael.Stahl@fresenius-kabi.com>; Author <author@noreply.github.com>
Betreff: Re: [mittelab/ifauthex-dokuwiki-plugin] Compatibility after update to Release rc2-2020-06-01 "Hogfather" RC2 (#5)


The new Hogfather RC3 is out, and the plugin seems to be working fine with it.

I also pushed the change for fixing compatibility with PHP 5.6. Until the next release, if you do not manage to update PHP, you can still install the master branch version of the plugin using this URL:
https://github.com/mittelab/ifauthex-dokuwiki-plugin/archive/master.zip

I will close this issue; if the problem persists, feel free to reopen this or open a new one!
