### ISSUE TITLE
Plugin breaks with PHP 5

### ISSUE THREAD

**Issue by zgtm** [mittelab/ifauthex-dokuwiki-plugin#7]
This Plugin does not work with PHP 5 on Debian 9.12

From the error log:

    [Wed Sep 30 22:59:00.211143 2020] [:error] [pid 20924] [client <IP>] PHP Catchable fatal error: 
    Argument 1 passed to AST\\tokenize() must be an instance of AST\\string, string given, called in
    <WIKIDIR>/lib/plugins/ifauthex/lib/grammar.php on line 202 and defined in <WIKIDIR>/lib/plugins
    /ifauthex/lib/tokenizer.php on line 134

Unfortunately, I had no time yet to look further into this. But I would love if this plugin could be made to work with PHP 5, as well and can probably help to get more insight into this in the next days.

**Comment by 5p4k** [comment]
Can you try with the current master version? the last commit should fix that.

I did not make a release yet because I was hoping to put odt support in, but did not find the time, so I may as well update it with this one commit.

**Comment by 5p4k** [comment]
I believe this should be fixed in the master (although it's not released yet). Feel free to reopen if this is not the case.
