### ISSUE TITLE
ifauthex does not change TOC

### ISSUE THREAD

**Issue by chrille69** [mittelab/ifauthex-dokuwiki-plugin#9]
Ifauthex does not change the table of contents. The chapters that ar hidden by ifauthex should not be visible for users in the table of contents.

Greeting
Christian

**Comment by mrhelbig** [comment]
Just wanting to bump this issue. I've just started using ifauthex and notice that this issue still seems to exist. I'd like to see the TOC only show content visible to the current user.

**Comment by 5p4k** [comment]
Right-I got sidetracked by my PhD dissertation and then other projects. I remember I had started looking into how the TOC is built. I will resume working on this
